package com.buzzware.zabellauser.ui.model

data class User(
    val authToken: String? = "",
    val avgRating: Int? = 0,
    var deviceType: String? = "Android",
    var email: String? = "",
    var password: String? = "",
    var image: String? = "",
    var id: String? = "",
    val isActive: Boolean? = false,
    val isAdminVerify: Boolean? = false,
    val isBio: Boolean? = false,
    var isOnline: Boolean? = false,
    val isNotify: Boolean? = false,
    val isRestaurantNotify: Boolean? = false,
    val isReviewNotify: Boolean? = false,
    val isStay: Boolean? = false,
    var stripeCustid: String? = "",
    val stripeStatus: String? = "",
    var token: String? = "",
    val totalRating: Int? = 0,
    var userDate: Long? = 0,
    var lat: Double? = 0.0,
    var lng: Double? = 0.0,
    var userName: String? = "",
    var userRole: String? = "",
    val vehicleId: String? = "",
    var phoneNumber: String? = "",
    var stripeaccount_id: String? = ""
)
